services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - mercedes-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "6969:80"  # Expose Nginx on port 6969 for frontend
    networks:
      - mercedes-network
    environment:
      - VUE_APP_BACKEND_URL=http://backend:8080  # Use backend service URL from Docker network
    depends_on:
      - backend  # Ensure backend is up before frontend starts

networks:
  mercedes-network:
    driver: bridge
